drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
drop table Service if exists
drop table ServiceCategory if exists
drop table UserAccount if exists
drop table UserDetail if exists
